DB/World: pandaren action bar
Legends-of-Azeroth/Legends-of-Azeroth-Pandaria-5.4.8 pull request #175
Opened 2023-11-22 09:36 UTC by zTerragor

DB/World: Fix missing 'Quaking Palm' pandaren mage action bar

2023-11-22 23:41 UTC, leelf00 commented on sql/updates/master/world/world_2023_11_10_13_33.sql
> +DELETE FROM `playercreateinfo_spell` WHERE `racemask`=8388608 AND `classmask`=64 AND `Spell`=403;
need check

2023-11-29 00:34 UTC, leelf00 requested changes
Where is this file from?

2024-06-28 18:53 UTC, jasongdove commented
@zTerragor Pandaren action bars for all classes were fixed with https://github.com/Legends-of-Azeroth/Legends-of-Azeroth-Pandaria-5.4.8/pull/268 - please confirm.

2024-07-02 06:46 UTC, leelf00 commented
Fixed by https://github.com/Legends-of-Azeroth/Legends-of-Azeroth-Pandaria-5.4.8/pull/268

2024-07-02 06:46 UTC, closed without merging