Database: Fix Lorvo and Aysa Quest Invis
Legends-of-Azeroth/Legends-of-Azeroth-Pandaria-5.4.8 pull request #182
Opened 2023-11-27 10:51 UTC by zTerragor

Database: Fix Lorvo and Aysa Quest Invis

2023-11-27 10:58 UTC, leelf00 commented
What is those npc creature entry?

2023-11-27 11:13 UTC, Err0r1 commented
```
SELECT guid, id, creature_template.name
FROM creature
LEFT JOIN creature_template ON creature.id=creature_template.entry
WHERE creature.guid = 224519;
```
guid	        id	        name
224519	44649	Twilight Centurion


GUID is wrong in the script

2023-11-27 11:46 UTC, leelf00 commented
Creature text already in db.

2023-11-29 00:31 UTC, leelf00 requested changes

2023-11-29 05:52 UTC, closed without merging